
import __ASTRO_IMAGE_IMPORT_lskwa from "./images/1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fencrypted-demo.md";
import __ASTRO_IMAGE_IMPORT_1fHQhK from "./images/1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly.md";
import __ASTRO_IMAGE_IMPORT_ZrWiYT from "./images/both-grid.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md";
import __ASTRO_IMAGE_IMPORT_Z2etLbX from "./images/both-list.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md";
import __ASTRO_IMAGE_IMPORT_Z2kTa1f from "./images/docusaurus.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md";
import __ASTRO_IMAGE_IMPORT_12Eczd from "./images/firefly1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md";
import __ASTRO_IMAGE_IMPORT_ZHAqBK from "./images/firefly2.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md";
import __ASTRO_IMAGE_IMPORT_Z2sQ4NI from "./images/firefly3.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md";
import __ASTRO_IMAGE_IMPORT_Z2lEQPE from "./images/github.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md";
import __ASTRO_IMAGE_IMPORT_DJQwz from "./images/left-grid3.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md";
import __ASTRO_IMAGE_IMPORT_27GenA from "./images/left-list.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md";
import __ASTRO_IMAGE_IMPORT_IWlki from "./images/masonry.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md";
import __ASTRO_IMAGE_IMPORT_1RQVjM from "./images/obsidian.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md";
import __ASTRO_IMAGE_IMPORT_Z1T20Ez from "./images/right-grid2.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md";
import __ASTRO_IMAGE_IMPORT_glozu from "./images/vitepress.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md";
export default new Map([["./images/1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fencrypted-demo.md", __ASTRO_IMAGE_IMPORT_lskwa], ["./images/1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly.md", __ASTRO_IMAGE_IMPORT_1fHQhK], ["./images/both-grid.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md", __ASTRO_IMAGE_IMPORT_ZrWiYT], ["./images/both-list.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md", __ASTRO_IMAGE_IMPORT_Z2etLbX], ["./images/docusaurus.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md", __ASTRO_IMAGE_IMPORT_Z2kTa1f], ["./images/firefly1.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md", __ASTRO_IMAGE_IMPORT_12Eczd], ["./images/firefly2.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md", __ASTRO_IMAGE_IMPORT_ZHAqBK], ["./images/firefly3.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md", __ASTRO_IMAGE_IMPORT_Z2sQ4NI], ["./images/github.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md", __ASTRO_IMAGE_IMPORT_Z2lEQPE], ["./images/left-grid3.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md", __ASTRO_IMAGE_IMPORT_DJQwz], ["./images/left-list.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md", __ASTRO_IMAGE_IMPORT_27GenA], ["./images/masonry.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md", __ASTRO_IMAGE_IMPORT_IWlki], ["./images/obsidian.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md", __ASTRO_IMAGE_IMPORT_1RQVjM], ["./images/right-grid2.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffirefly-layout-system.md", __ASTRO_IMAGE_IMPORT_Z1T20Ez], ["./images/vitepress.avif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fmarkdown-extended.md", __ASTRO_IMAGE_IMPORT_glozu]]);
		